Allow .git-vsn file to override behaviour

diff --git a/git-vsn b/git-vsn
--- a/git-vsn
+++ b/git-vsn
@@ -12,6 +12,36 @@ if [ -n "$GIT_VSN" ]; then
     exit 0
 fi
 
+# look up the directory tree for a particular file;
+# return the directory it was found in.
+search_up() {
+    local look=${PWD%/}
+
+    while [[ -n $look ]]; do
+        [[ -e $look/$1 ]] && {
+            printf '%s\n' "$look"
+            return
+        }
+
+        look=${look%/*}
+    done
+
+    [[ -e /$1 ]] && echo /
+}
+
+if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+    # we're not in a work tree, so we can't figure out the version.
+    # hopefully there's a .git-vsn file somewhere to tell us.
+    git_vsn_file="$(search_up ".git-vsn")/.git-vsn"
+    if [ -f "$git_vsn_file" ]; then
+        head "$git_vsn_file"
+        exit 0
+    else
+        echo "Error: not in git work tree; cannot find .git-vsn file"
+        exit 1
+    fi
+fi
+
 # refresh the index
 git status >/dev/null 2>&1
 
